imports:
  - { resource: ./application.yaml }

services:
  User.EnvironmentArranger:
    class: ../../tests/modules/Shared/infrastructure/mongo/MongoEnvironmentArranger
    arguments: ['@Shared.ConnectionManager']

  Shared.EventBus:
    class: ../../modules/Shared/infrastructure/EventBus/InMemory/InMemorySyncEventBus
    arguments: []
