services:

  User.UserRepository:
    class: ../../../../modules/Users/infrastructure/persistence/MongoUserRepository
    arguments: ['@Shared.ConnectionManager']

  User.UserCreator:
    class: ../../../../modules/Users/application/Create/UserCreator
    arguments: ['@User.UserRepository']

  User.LoginUser:
    class: ../../../../modules/Users/application/Login/LoginUser
    arguments: ['@User.UserRepository']

  User.CreateUserCommandHandler:
    class: ../../../../modules/Users/application/Create/CreateUserCommandHandler
    arguments: ['@User.UserCreator']
    tags:
      - { name: 'commandHandler' }

  User.LoginUserCommandHandler:
    class: ../../../../modules/Users/application/Login/LoginUserCommandHandler
    arguments: ['@User.LoginUser']
    tags:
      - { name: 'commandHandler' }
