services:

  Shared.Logger:
    class: ../../../../modules/Shared/infrastructure/WinstonLogger
    arguments: []
  
  Shared.CommandHandlersInformation:
    class: ../../../../modules/Shared/infrastructure/CommandBus/CommandHandlersInformation
    arguments: ['!tagged commandHandler']

  Shared.CommandBus:
    class: ../../../../modules/Shared/infrastructure/CommandBus/InMemoryCommandBus
    arguments: ['@Shared.CommandHandlersInformation']