services:

  User.controllers.UserPutController:
    class: ../../controllers/UserPutController
    arguments: ["@Shared.CommandBus"]

  User.controllers.UserLogoutController:
    class: ../../controllers/UserLogoutController
    arguments: ["@Shared.CommandBus"]

  User.controllers.UserLoginController:
    class: ../../controllers/UserLoginController
    arguments: ["@Shared.CommandBus"]

  User.controllers.StatusGetController:
    class: ../../controllers/StatusGetController
    arguments: []